### ISSUE TITLE
Leverage existing protocol and vocabulary for federation

### ISSUE THREAD

**Issue by swift2plunder** [nektro/aquila#1]
IIRC, federation is still TODO. Email and XMPP are options, but would require developing a vocabulary and may involve installing additional services. This issue is to recommend ForgeFed, an Activity Pub extension for social coding that operates over HTTPS:

https://github.com/forgefed/forgefed

**Comment by nektro** [comment]
Aquila in its current iteration is not a git server and so forgefed would not make sense for the project at this time.

**Comment by swift2plunder** [comment]
Thank you for taking the time to review my recommendation. Even though it doesn't make sense for your project in the strict sense of code or concepts that you can directly reuse, my hope was that you might find the idea of leveraging an existing vocabulary for managing collections useful when designing federation, as opposed to mechanisms like ReST, where endpoints and data formats are constantly reinvented without any built-in discovery mechanism

Please feel free to reopen this thread or otherwise contact me if you'd like help designing and documenting federation that uses this approach

**Comment by nektro** [comment]
the base protocol of Activity Pub may still prove useful, we will see as that gets closer. the immediate roadmap I'm working on is porting the app from Go to Zig. but once that is ready the following features will yield themselves very well to the federation.
