### ISSUE TITLE
To stop auto release

### ISSUE THREAD

**Issue by eldesh** [nektro/aquila#18]
I want to stop importing releases on aquila.red without permission when I push to my repository.
My package version is 0.3, but I never intended to release 0.3.

**Comment by nektro** [comment]
part of Aquila/Zigmod's philosophy is supporting the latest changes. supporting a flow of tagged releases upstream is planned but low priority at this time

**Comment by nektro** [comment]
the number only represent the increment of updates. once the CI feature becomes available shortly, this number will be a confirmation that any 'version' published on Aquila has passed all of the project's tests as well

**Comment by eldesh** [comment]
Thank you for your reply.
I will wait for the release of the CI feature.
And I may be able to contribute if the issue is well documented.
